# Generated by Django 3.1.6 on 2021-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='estate_id',
            new_name='estate',
        ),
        migrations.AddField(
            model_name='item',
            name='discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='donate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='wanted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='wanted_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
